<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class topedController extends Controller
{
    //https://gql.tokopedia.com/   POST
    //[{"operationName":"SearchProductQuery","variables":{"params":"scheme=https&device=desktop&related=true&q=jaket%20pria&source=universe&st=product&page=2&ob=23&variants=&shipping=&start=60&rows=60&user_id=5023630&unique_id=7f0c062573000584f7125501374729a0&safe_search=false"},"query":"query SearchProductQuery($params: String) {\n  searchProduct(params: $params) {\n    source\n    totalData: count\n    totalDataText: count_text\n    additionalParams: additional_params\n    redirection {\n      redirectionURL: redirect_url\n      departmentID: department_id\n      __typename\n    }\n    responseCode: response_code\n    keywordProcess: keyword_process\n    suggestion {\n      suggestion\n      suggestionCount\n      currentKeyword\n      instead\n      insteadCount\n      suggestionText: text\n      suggestionTextQuery: query\n      __typename\n    }\n    related {\n      relatedKeyword: related_keyword\n      otherRelated: other_related {\n        keyword\n        url\n        __typename\n      }\n      __typename\n    }\n    isQuerySafe\n    ticker {\n      text\n      query\n      typeID: type_id\n      __typename\n    }\n    products {\n      id\n      name\n      childs\n      url\n      imageURL: image_url\n      imageURL300: image_url_300\n      imageURL500: image_url_500\n      imageURL700: image_url_700\n      price\n      priceRange: price_range\n      category: department_id\n      categoryID: category_id\n      categoryName: category_name\n      categoryBreadcrumb: category_breadcrumb\n      discountPercentage: discount_percentage\n      originalPrice: original_price\n      shop {\n        id\n        name\n        url\n        isPowerBadge: is_power_badge\n        isOfficial: is_official\n        location\n        city\n        reputation\n        clover\n        __typename\n      }\n      wholesalePrice: whole_sale_price {\n        quantityMin: quantity_min\n        quantityMax: quantity_max\n        price\n        __typename\n      }\n      courierCount: courier_count\n      condition\n      labels {\n        title\n        color\n        __typename\n      }\n      labelGroups: label_groups {\n        position\n        type\n        title\n        __typename\n      }\n      badges {\n        title\n        imageURL: image_url\n        show\n        __typename\n      }\n      isFeatured: is_featured\n      rating\n      countReview: count_review\n      stock\n      GAKey: ga_key\n      preorder: is_preorder\n      wishlist\n      shop {\n        id\n        name\n        url\n        goldmerchant: is_power_badge\n        location\n        city\n        reputation\n        clover\n        official: is_official\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}]
}
